# Generated by Django 5.0.6 on 2024-06-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='image/default.jpg', upload_to='image/', verbose_name='Avataras'),
        ),
    ]
