# Generated by Django 5.0.6 on 2024-06-06 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='size',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Tipas'),
        ),
    ]
