# Generated by Django 5.0.6 on 2024-06-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_size_subcategory_size_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='Ar išpardavime?'),
        ),
        migrations.AlterField(
            model_name='footwear',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='Ar išpardavime?'),
        ),
        migrations.AlterField(
            model_name='otherproduct',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='Ar išpardavime?'),
        ),
    ]
