# Generated by Django 5.0.6 on 2024-06-06 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_clothing_is_on_sale_alter_footwear_is_on_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='Pažymėti, jei prekė yra išpardavime'),
        ),
        migrations.AlterField(
            model_name='footwear',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='Pažymėti, jei prekė yra išpardavime'),
        ),
        migrations.AlterField(
            model_name='otherproduct',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='Pažymėti, jei prekė yra išpardavime'),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Tipas'),
        ),
    ]
