# Generated by Django 5.0.6 on 2024-06-06 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_clothing_is_on_sale_alter_footwear_is_on_sale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='Ar išpardavime?'),
        ),
        migrations.AlterField(
            model_name='footwear',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='Ar išpardavime?'),
        ),
        migrations.AlterField(
            model_name='otherproduct',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='Ar išpardavime?'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Įvertinimas')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Atsiliepimas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('clothing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.clothing', verbose_name='Drabužis')),
                ('footwear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.footwear', verbose_name='Avalynė')),
                ('otherproduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.otherproduct', verbose_name='Kita')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vartotojas')),
            ],
            options={
                'verbose_name': 'Atsiliepimas',
                'verbose_name_plural': 'Atsiliepimai',
            },
        ),
    ]
