# Generated by Django 5.0.6 on 2024-06-06 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Prekės papildoma nuotrauka', 'verbose_name_plural': 'Prekės papildomos nuotraukos'},
        ),
    ]
