# Generated by Django 5.0.6 on 2024-06-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_productimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Spalva')),
            ],
            options={
                'verbose_name': 'Prekės spalva',
                'verbose_name_plural': 'Prekės spalvos',
            },
        ),
        migrations.AddField(
            model_name='clothing',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Ar prekė yra?'),
        ),
        migrations.AddField(
            model_name='footwear',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Ar prekė yra?'),
        ),
        migrations.AddField(
            model_name='otherproduct',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Ar prekė yra?'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='colors',
            field=models.ManyToManyField(blank=True, to='store.color', verbose_name='Spalvos'),
        ),
        migrations.AddField(
            model_name='footwear',
            name='colors',
            field=models.ManyToManyField(blank=True, to='store.color', verbose_name='Spalvos'),
        ),
        migrations.AddField(
            model_name='otherproduct',
            name='colors',
            field=models.ManyToManyField(blank=True, to='store.color', verbose_name='Spalvos'),
        ),
    ]
