# Generated by Django 5.0.6 on 2024-06-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_color_clothing_is_available_footwear_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherproduct',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Kiekis sandėlyje'),
        ),
    ]
