# Generated by Django 5.1.1 on 2024-10-07 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_clothing_options_alter_footwear_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Tėvinė kategorija', 'verbose_name_plural': 'Tėvinės kategorijos'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name'], 'verbose_name': 'Prekės spalva', 'verbose_name_plural': 'Prekės spalvos'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Vaikinė kategorija', 'verbose_name_plural': 'Vaikinė kategorija'},
        ),
    ]
