# Generated by Django 5.0.6 on 2024-06-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paysera', 'Paysera sąskaita'), ('swedbank', 'AB "Swedbank" bankas'), ('seb', 'AB bankas "SEB"'), ('luminor', 'Luminor'), ('siauliu', 'AB "Šiaulių bankas"'), ('revolut', 'Revolut (LT)'), ('citadele', 'AS "Citadele bankas"'), ('urbo', 'UAB Urbo bankas'), ('lku', 'Lietuvos centrinė kredito unija'), ('n26', 'N26 Bank (LT)')], default='paysera', max_length=50, verbose_name='Apmokėjimo būdas'),
        ),
    ]
